name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # O la rama que uses

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./   # La carpeta raíz del repo, donde está index.html
